### ISSUE TITLE
State of iOS app?

### ISSUE THREAD

**Issue by pwFoo** [tinode/ios#1]
I like tinode and a friend would like to use an iPhone app.
Is there a app ready for Install / testing or is it WIP?

**Comment by or-else** [comment]
This is the only iOS Tinode client that I know of that's openly available right now. Ask @aforge for progress and plans.

**Comment by aforge** [comment]
@pwFoo 
I'm working on a prototype in my spare time. I'm hoping to get a basic version ready by the EoY.
The goal ATM is feature parity with Tindroid.
If you have experience with iOS development and would like to help, let me know.

**Comment by or-else** [comment]
The app is available in appstore:
https://apps.apple.com/us/app/tinode/id1483763538

Closing.
