### ISSUE TITLE
File uploading and taking photo

### ISSUE THREAD

**Issue by Kuvonchbeky** [tinode/ios#118]
Files don't upload (out of band). Tested on iOS 12.4.3. MessageCell for file is once display and disappear.
In topic, click "+" attachment button -> "Image" -> "Take Photo" and app closed

**Comment by aforge** [comment]
@Kuvonchbeky Can you pull from devel branch, rebuild and run this test again please? I believe the crash when accessing the camera has been fixed.
How large is the file are you trying to send as attachment?

**Comment by Kuvonchbeky** [comment]
File size is 1.1 MB
If secure connection disabled then nothing happens when try to send file

And if secure connection enabled app throw exception when choose file for upload it:
``` Fatal error: Unexpectedly found nil while unwrapping an Optional value: file 
/Users/macminidm/Desktop/Tinodios/Tinodios/LargeFileHelper.swift, line 52
2019-12-09 16:33:59.130253+0500 Tinodios[8411:188883] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/macminidm/Desktop/Tinodios/Tinodios/LargeFileHelper.swift, line 52
```

**Comment by aforge** [comment]
This can happen when you aren't authenticated. I'll try to reproduce later today.

**Comment by aforge** [comment]
I've been able to send a file (1.5M) successfully over a secure connection. No problem at all.
Can you provide instructions to reproduce please?

**Comment by Kuvonchbeky** [comment]
I'm using: Remote server, Simulator iPhone 8 13.2.2, secure connection. I have taken up pull from devel branch. File size is 1.3 MB

Same result (crash):
> File size is 1.1 MB
> If secure connection disabled then nothing happens when try to send file
> 
> And if secure connection enabled, then app throws exception when choose file for upload:
> 
> ```
> /Users/macminidm/Desktop/Tinodios/Tinodios/LargeFileHelper.swift, line 52
> 2019-12-09 16:33:59.130253+0500 Tinodios[8411:188883] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/macminidm/Desktop/Tinodios/Tinodios/LargeFileHelper.swift, line 52
> ```

**Comment by or-else** [comment]
The crash is due to the missing authentication token.  It should not crash on missing token. But if the token is missing the upload won't work even if the crash is fixed.

Do you know why you are not logged in when you upload the photo?

**Comment by Kuvonchbeky** [comment]
> The crash is due to the missing authentication token. It should not crash on missing token. But if the token is missing the upload won't work even if the crash is fixed.
Yes, auth token is nill

> Do you know why you are not logged in when you upload the photo?
No, I don't know why so. But logcat shows this:
```
CFNetwork SSLHandshake failed (-9847)
TCP Conn 0x60000083e280 SSLHandshake failed (-9847)
[default] Tinode network error: The operation couldn’t be completed. (SwiftWebSocket.WebSocketError error 0.)
CFNetwork SSLHandshake failed (-9847)
TCP Conn 0x60000083b480 SSLHandshake failed (-9847)
[default] Tinode network error: The operation couldn’t be completed. (SwiftWebSocket.WebSocketError error 0.)
[DocumentManager] Failed to associate thumbnails for picked URL file:///Users/macminidm/Library/Developer/CoreSimulator/Devices/BE6361CD-6496-4209-9123-A57895AD8E86/data/Containers/Shared/AppGroup/4A951A7C-1858-448A-9472-6D20E8935C6A/File%20Provider%20Storage/Downloads/Snake_Wrangling_for_Kids_Learning.pdf with the Inbox copy file:///Users/macminidm/Library/Developer/CoreSimulator/Devices/BE6361CD-6496-4209-9123-A57895AD8E86/data/Containers/Data/Application/B02BCEF7-542E-4DC6-84E5-A0703B6A6C7A/tmp/co.tinode.tinodios-test-Inbox/Snake_Wrangling_for_Kids_Learning.pdf: Error Domain=QLThumbnailErrorDomain Code=102 "(null)" UserInfo={NSUnderlyingError=0x60000320ba80 {Error Domain=GSLibraryErrorDomain Code=3 "Generation not found" UserInfo={NSDescription=Generation not found}}}

```
before that 

> "...LargeFileHelper.swift, line 52"

 error

**Comment by or-else** [comment]
Your server is likely not set up correctly. The attempt to login fails. 

Can you connect to your server over https using webapp?

**Comment by Kuvonchbeky** [comment]
> Your server is likely not set up correctly. The attempt to login fails.
> 
> Can you connect to your server over https using webapp?

No, I cannot connect web client currectly, it doesn't working

**Comment by or-else** [comment]
So, your server is not set up correctly for https.

**Comment by Kuvonchbeky** [comment]
Can I use iOS Client without https?

**Comment by Kuvonchbeky** [comment]
> So, your server is not set up correctly for https.

Thanks, I will correct it

**Comment by or-else** [comment]
> Can I use iOS Client without https?

Yes.

**Comment by Kuvonchbeky** [comment]
Thank you
