### ISSUE TITLE
<head> missing in MessageDb

### ISSUE THREAD

**Issue by Kuvonchbeky** [tinode/ios#129]
Head values missing in this line: https://github.com/tinode/ios/blob/devel/TinodiosDB/MessageDb.swift#L209
I think Tinode.deserializeObject(from: r[self.head]) eqalizing JSON object to nill.

**Comment by Kuvonchbeky** [comment]
I suppose, exactly this at this line: https://github.com/tinode/ios/blob/devel/TinodeSDK/Tinode.swift#L1207 `d` value equalized non nil value for head.

**Comment by Kuvonchbeky** [comment]
Actually, the problem is in `parts[0] == String(describing: T.self)` debugger shows that `parts[0] = Optional<Dictionary<String, JSONValue>` and `String(describing: T.self)) = Dictionary<String, JSONValue>` that is why it returning `nil` value.

**Comment by aforge** [comment]
So it writes the type as Optional during serialization which is not good.

**Comment by aforge** [comment]
I think this should take care of it:
https://github.com/tinode/ios/commit/fbd4a06306674d84b65ea3f379805a7a6348ae6f
