### ISSUE TITLE
Sync contacts as soon as they change

### ISSUE THREAD

**Issue by or-else** [tinode/ios#135]
https://stackoverflow.com/questions/48343157/get-only-new-modified-phone-contacts-from-iphone
https://github.com/tinode/chat/issues/343

**Comment by aforge** [comment]
https://github.com/tinode/ios/commit/ba708b407285ee7367cffc51c3710a1869852a13
https://github.com/tinode/ios/commit/3a038db468db712fa81142a70056b37850ab0483
