### ISSUE TITLE
Changing media representation to "View" instead of in text

### ISSUE THREAD

**Issue by YKuvonchbek** [tinode/ios#142]
I think, for each message type should has a specific message cell like `AttachmentMessageCell`, `ImageMessageCell`, `VideoMessageCell`, `AudioMessageCell` , `QuoteMessageCell` and etc. And also inline images should serve only for thumbnail of photo messages and video messages. 

`UITableView` more compatible rather than `UICollectionView` for message list.

**Comment by or-else** [comment]
> each message type should has a specific message cell

Maybe. 

The message is sent as Drafty which is essentially a rich text format, like HTML or RTF or PDF, but much simpler. The client application just renders it. For example, I recently enabled sending images with captions and rendering just works right away on all platforms

If you want to use custom formatters for different type of messages then it's a restriction. You could implement such custom renderers as an optimization. But then if you want to use just them then the transmission format (Drafty) needs to be restricted to just this type of content.

What if someone sends a message with both an image and an audio?

> inline images should serve only for thumbnail of photo messages and video messages

Again, maybe. Depends on implementation. Do you have something to show? More more detailed description of what you have in mind?

> `UITableView` more compatible rather than `UICollectionView` for message list.

What is going to be gained by replacing `UICollectionView` with `UITableView`?

I think https://groups.google.com/forum/#!forum/tinode is more suitable for this conversation.
