### ISSUE TITLE
TinodiosNSExtension not working and notice not shown

### ISSUE THREAD

**Issue by hamedvbv** [tinode/ios#187]
When we do these:
1.run TinodiosNSExtension with Tinode.app
2.log in with bob account.
3.send the app to the background.
4.set a breakpoint on didReceive() function in [TinodiosNSExtension/NotificationService.swift](https://github.com/tinode/ios/blob/8d779a579aba9a4a19ab1de0b1405642146751f4/TinodiosNSExtension/NotificationService.swift#L20).
5.send a message from frank to bob using another device or browser.

result:
badge increased on Tinode.app but breakpoint not issued and notification not shown in notification center.

consider:
I checked this by sending push notification manually in firebase (mutable-content:1, alert:{title,body}) , this work and breakpoint issued but because it didn't have enough payload, in line 44, exited. 

any suggestion?

**Comment by aforge** [comment]
Thanks for reporting. What server and client versions did you use?

**Comment by hamedvbv** [comment]
Thanks, I Use:
Server: 0.20
iOS client: 1.2.0

**Comment by or-else** [comment]
1.2.0 can't be right. That's from 2 years ago:
https://github.com/tinode/ios/releases/tag/v1.2.0

**Comment by hamedvbv** [comment]
It's my mistake.

the version I used is v1.10.3
[https://github.com/tinode/ios/tree/v1.10.3](https://github.com/tinode/ios/tree/v1.10.3)

**Comment by aforge** [comment]
I cannot reproduce this behavior. Is it reproducible on your side in a stable manner?

When sent into the background, my extension still triggers the breakpoint and presents the alert in the notifications center as well as increases the badge counter upon me sending a message to the client.

Also note that if you tested this scenario right after installing the app on the device, it may take several minutes for the device into to propagate through FCM/APS.

**Comment by or-else** [comment]
@hamedvbv It's been nearly two weeks. Any update on this?
