### ISSUE TITLE
Login token is not refreshed on loginToken

### ISSUE THREAD

**Issue by or-else** [tinode/ios#19]
@aforge 

It looks like the authentication token returned by the server is saved to Keychain only in case of `loginBasic`. It's not updated when `loginToken` is used.

**Comment by aforge** [comment]
Correct. The logic of updating tokens was something that I left to implement for myself in the future.
But thanks for reminding.

**Comment by aforge** [comment]
This should take care of it: https://github.com/tinode/ios/commit/dc99da19059cf8bf3ef77f53b7b7d6e48164f3c5
