### ISSUE TITLE
ios cannot get topic from android create

### ISSUE THREAD

**Issue by heavy-snowy** [tinode/ios#191]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/38177962/210952400-bf4e5793-a36b-4160-a8b2-4e00fd634425.png">
use this api,ios user only can get topic list from ios  user create.

**Comment by or-else** [comment]
You did not provide much information in your report, but I suspect you misunderstood the purpose of the `getFilteredTopics` method. It doesn't send any network requests. It filters topics cached at the device. It won't return a topic that you have not subscribed to.

Please use forum for questions. If you still believe there is a bug, please file a real bug report with steps to reproduce and logs.
