### ISSUE TITLE
unsupported version qKpY7029b1Q

### ISSUE THREAD

**Issue by young310** [tinode/ios#198]
**Describe the bug**
iOS client will stuck in log in screen after click on login button
Server will show unsupported version

**To Reproduce**
1. Go to IOS client
2. input id and password
3. click sign in button

**Expected behavior**
Log in to the app and show chat list

**Screenshots**
<img width="511" alt="Screenshot 2023-03-26 at 20 25 33" src="https://user-images.githubusercontent.com/8056293/227775484-084f1ea8-791a-4bca-8e94-6152a489bdfa.png">

**Tinodios (please complete the following information):**
 - Version v1.12.0 and 47022aedac4dc132a32561a898c15c9856b09199
 - Device Simulator and iPhone 11 prox max
 - iOS version, 16.3.1

**Server**
- Type: my own setup
- Server type:  unmodified 
- Server version: v0.22.4

**Additional context**
Server Console:
I2023/03/26 20:18:06 ws: session started qKpY7029b1Q 36.231.179.204:53435 1
I2023/03/26 20:18:06 in: '{"hi":{"ua":"Tinodios/1698 (iOS 16.4; en); tinode-swift/1.12.0-rc1","id":"67881","lang":"en","ver":"0.18"}}' sid='qKpY7029b1Q' uid=''
W2023/03/26 20:18:06 s.hello: unsupported version qKpY7029b1Q
I2023/03/26 20:23:32 ws: session started bxDkbFpzt74 36.231.179.204:53805 1
I2023/03/26 20:23:33 in: '{"hi":{"ua":"Tinodios/1706 (iOS 16.4; en); tinode-swift/1.11.3","id":"89668","lang":"en","ver":"0.18"}}' sid='bxDkbFpzt74' uid=''
W2023/03/26 20:23:33 s.hello: unsupported version bxDkbFpzt74

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/ios/commit/73a8aa373363c1c268ba86799aede303b5ae4306
Thanks.
