### ISSUE TITLE
Invalid phone numbers sent to the server

### ISSUE THREAD

**Issue by or-else** [tinode/ios#20]
It looks like the contacts sync does not produce E.164-compliant phone numbers. The country code is missing:
```
query = tel:+5555648583,tel:+4155553695,tel:+5554787672,tel:+4085555270
```

**Comment by aforge** [comment]
Fixed by
https://github.com/tinode/ios/commit/4cbe7cc16cb63add6e1577842937e151ef5c4859

**Comment by aforge** [comment]
Note however that the phone numbers on the server are stored without a +. Should we fix it as well?

**Comment by or-else** [comment]
The server-side issue was a data issue. It was fixes a while ago:
https://github.com/tinode/chat/commit/04a2a95a3870a203c17d80bd528f76928e8c777d

The server itself does not care about format of phone numbers.
