### ISSUE TITLE
Connection to server lost

### ISSUE THREAD

**Issue by blasius** [tinode/ios#200]
**Describe the bug**
On iOS 15.2, I installed Tinode after a previous version was showing me this message: Connection to server lost. I removed Tinode, and reinstalled it via the AppStore. I logged in successfully but after that it showed me the same message. Even after rebooting my iPhone the message is the same.

**To Reproduce**
1. Open TinodeIos
2. Login in if not already logged in
3. Wait up to 5 seconds
4. A message should appear in the form of a snack-bar saying: Connection to server lost

**Expected behavior**
I should be able to chat and call normally, which I can't do with that message

**Screenshots**

**Tinodios (please complete the following information):**
 - Version [latest version on the AppStore]
 - Device [iPhone 7]
 - iOS version, 15.2

**Server**
- Type [api.tinode.co]
- Server type [unmodified]
- Server version [Official]

**Additional context**
I don't have access to any logs

**Comment by aforge** [comment]
I just followed installed the latest version of the app from App Store and it worked fine for me.

Out of curiosity, does this message keep popping up while the app is open?
And how is it preventing you from chatting/calling? Will it just not go away and cover the text input bar?
Or is it that the app cannot connect to the server?

I assume your internet connection is stable.

**Comment by blasius** [comment]
Yes it does cover up the input field and keeps popping up again and again. If I am fast enough I can touch the input field and be able to write a message but at the same time the bottom of the keyboard is covered and I can't type for example the space button. 

And when I press call the call screen appears but is dismissed almost immediately.

**Comment by aforge** [comment]
That's weird. It appears you phone repeatedly keeps losing and restoring connection to the server.

Is there a chance you can test it with another device? We haven't observed this behavior on iPhone 8+, and I don't have an iPhone 7 right now unfortunately.
I am wondering whether it's something to do with iPhone 7 specifically.

**Comment by blasius** [comment]
Let me borrow another iPhone and I'll come back with results

**Comment by or-else** [comment]
No update in over a month. Is this still relevant?
