### ISSUE TITLE
iOS App Crashed when signing up

### ISSUE THREAD

**Issue by damoncoo** [tinode/ios#205]
## If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.

**Describe the bug**
App crashes when signing up

**To Reproduce**
1. Go to 'SignUp'
2. Click on 'SignUp'
3. Crashes

**Expected behavior**
No Crash

**Screenshots**
<img width="1214" alt="截屏2023-06-05 23 19 38" src="https://github.com/tinode/ios/assets/4880373/a720786d-c1b8-454e-8a08-220a5d8a1fc9">

**Tinodios (please complete the following information):**
 - Version [e.g. 0.22]
 - Device [e.g. Simulator iPhone 14 Pro]
 - iOS version,  16.4

**Server**
- Server type web.tinode.co
- Server version 0.22.8

**Additional context**
No Token

**Comment by aforge** [comment]
Thanks for reporting.
https://github.com/tinode/ios/commit/f8cb428951ef5b49f24db64726f7f1966c36e996

LMK if you see it again.

**Comment by or-else** [comment]
@aforge I think there is more to it. The server indeed did not return the token when it should have. Please take a look at the log in the attached picture. It seems like `Acc.Login` was treated as if it was `false`.

**Comment by or-else** [comment]
@damoncoo What do you use for a server?

**Comment by damoncoo** [comment]
> @damoncoo What do you use for a server?

I am using web.tinode.co, also tried api.tinode.co

**Comment by damoncoo** [comment]
I changed the email with different one, it worked.  

I think it is the email issue, the email I used to sign up is already registered with another user. When I sign up with different user id but same email, it gives the error.  Since the email is unique, it should not reply with successful message.

**Comment by or-else** [comment]
Thanks. I was able to reproduce server-side error.

**Comment by or-else** [comment]
I believe it's completely fixed.
