### ISSUE TITLE
Farsi / Persian translation

### ISSUE THREAD

**Issue by kfatehi** [tinode/ios#207]
Hi, nice work on this project.
I have a Mac w/ the latest Xcode and I'd be willing to work on the Farsi language translation for iOS.
After completing it I am happy to move on to the other clients as well.
Thanks,
Keyvan

**Comment by or-else** [comment]
Great, looking forward to translation.

**Comment by kfatehi** [comment]
Unfortunately I did not manage to successfully deploy the platform during the time I had available which has since run out. Closing as a result
