### ISSUE TITLE
IOS Push Notification Badge only. No Banner

### ISSUE THREAD

**Issue by jeermainedb** [tinode/ios#209]
**Describe the bug**
We are currently testing the push notification feature of IOS. Android works fine. But IOS only received BADGE update.
Tried the manual push notif from Firebase console, both IOS and Android works fine though. Only through tinode that is not working properly.

**To Reproduce**
1. Trigger push notif (new message/create new msg)
2. Receives Badge update ONLY... NO BANNER

**Expected behavior**
Receive both banner notification "new msg" and "badge update"

**Screenshots**
Badge Only
![IMG_96179D95241F-1](https://github.com/tinode/ios/assets/130530580/cc66a240-200f-4494-94f1-eb4172a71b7d)

Manual Push Trigger via Firebase Console
![IMG_69EB3766A68A-1](https://github.com/tinode/ios/assets/130530580/5a58fd1b-a86d-42ae-a2df-ddcc9ed3d07f)

**Log**
`didReceiveRemoteNotification {
    aps =     {
        badge = 1;
        "content-available" = 1;
        "interruption-level" = "time-sensitive";
        "mutable-content" = 1;
        sound = default;
        "thread-id" = usrsSX4cmr4VTE;
    };
    content = "Tinode Notif Trigger LOG";
    "gcm.message_id" = 1700637725393264;
    "google.c.fid" = "dK6niob_-ky-pr9nUSTWoV";
    "google.c.sender.id" = 224125586230;
    rc = "{\"txt\":\"Tinode Notif Trigger LOG\"}";
    seq = 217;
    topic = usrsSX4cmr4VTE;
    ts = "2023-11-22T07:22:05.171Z";
    what = msg;
    xfrom = usrsSX4cmr4VTE;
}`

**Tinodios (please complete the following information):**
 - Version 1.2.0 (1727)
 - Device iPhoneX and iPhone13 
 - iOS version 15 and 17Beta

**Comment by or-else** [comment]
Can you reproduce the problem with the stock app pointed at sandbox.tinode.co or api.tinode.co?

**Comment by wildiostonight** [comment]
> Can you reproduce the problem with the stock app pointed at sandbox.tinode.co or api.tinode.co?

We cant reproduce push notification on sandbox since they have a different config for firebase.

**Comment by or-else** [comment]
What do you mean? Are you saying sandbox pushes do not work with a stock app?

**Comment by wildiostonight** [comment]
> What do you mean? Are you saying sandbox pushes do not work with a stock app?

yes. tested it on both android and ios. Since firebase handler/account has a different settings from sandbox.

**Comment by Kevdevopsnewbie** [comment]
As I mentioned on the Tinode General group, any changes to the server side configuration do not have any effect on the output.

**Comment by or-else** [comment]
> > Are you saying sandbox pushes do not work with a stock app?
> yes. tested it on both android and ios.
> tested on our own server, android works fine. ios, only badge

I understand something does not work with your server setup. That is not what I'm asking. 

Once again, can you reproduce the problem with a stock iOS app pointed at sandbox.tinode.co or api.tinode.co?
Please give direct and clear answer: 

1. The new message banner does NOT appear in the stock iOS app which is pointed to sandbox (or api). 
2. The new message banner APPEARS in the stock iOS app which is pointed to sandbox (or api).  

Your answer:

**Comment by wildiostonight** [comment]
> > > Are you saying sandbox pushes do not work with a stock app?
> 
> > yes. tested it on both android and ios.
> > tested on our own server, android works fine. ios, only badge
> 
> I understand something does not work with your server setup. That is not what I'm asking.
> 
> Once again, can you reproduce the problem with a stock iOS app pointed at sandbox.tinode.co or api.tinode.co? Please give direct and clear answer:
> 
> 1. The new message banner does NOT appear in the stock iOS app which is pointed to sandbox (or api).
> 2. The new message banner APPEARS in the stock iOS app which is pointed to sandbox (or api).
> 
> Your answer:

No notification/banner/badge pointed on sandbox with the stock iOS app.

**Comment by or-else** [comment]
![3alkz3kl2neis](https://github.com/tinode/ios/assets/5938143/83659fc8-8bff-4b97-a0c3-6e71ef2c15b6)

Works for me.

**Comment by wildiostonight** [comment]
> ![3alkz3kl2neis](https://private-user-images.githubusercontent.com/5938143/285620482-83659fc8-8bff-4b97-a0c3-6e71ef2c15b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDA5NTUxMjQsIm5iZiI6MTcwMDk1NDgyNCwicGF0aCI6Ii81OTM4MTQzLzI4NTYyMDQ4Mi04MzY1OWZjOC04YmZmLTRiOTctYTBjMy02ZTcxZWYyYzE1YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjVUMjMyNzA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWFkYzE3Y2QwNGZhZTI4NDMyODhmZmM2YmFmMTc2NDJiZWMzYTU4ZWY5ZjIzYTViN2UzNGI4OWI5YjIxZGRhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p7UtEQ51T7xy_06Cj2y46BLMmoWed8dKAFG-jDxfM2M)
> 
> Works for me.

Wow. so aside from firebase setup. what should be adjust to the stock app in order for the notification to work?
