### ISSUE TITLE
App freezes in launchscreen

### ISSUE THREAD

**Issue by aforge** [tinode/ios#24]
Sometimes the app freezes and hangs in the launchscreen after sending a {hi} request to the server and not receiving a response (when we have an auth token saved on the device).
Implement future timeouts to prevent such problems from happening.

**Comment by or-else** [comment]
I suppose this should be done in Android as well.

**Comment by or-else** [comment]
And webapp

**Comment by or-else** [comment]
Fixed it in Android: https://github.com/tinode/tindroid/commit/dac8e1f02c21f38f05e2923d4e2056f53ce49642#diff-56c0ce8298a3482df5af2f2ae7a65ae2R173

**Comment by aforge** [comment]
Nice. Do you want to run it once a second?
I think something like 10 seconds should do.

**Comment by aforge** [comment]
Added similar logic in iOS: 83fbad0

**Comment by or-else** [comment]
> Nice. Do you want to run it once a second? 

I don't think it matters much. When the queue is empty it exits very quickly. 10 sec is an overkill though. It means some promises won't be expired for 15 seconds.

Ideally it should not run at all if the queue is empty. I.e. if the queue is empty, stop the timer, restart it when something is added to queue.

**Comment by aforge** [comment]
Right. My main concern here is the battery.
Anyway, I've reduced the iOS interval down to 3 seconds. Closing this bug.
