### ISSUE TITLE
Some users are missing in Find-local and New Group-members views

### ISSUE THREAD

**Issue by or-else** [tinode/ios#28]
iOS client shows just 4 results in Find and New Group members views while Android shows 6:

https://github.com/tinode/tindroid/blob/master/android-find-people.png
https://github.com/tinode/tindroid/blob/master/android-new-topic.png

**Comment by aforge** [comment]
Were you logged in as alice?

**Comment by or-else** [comment]
Yes, as Alice.

**Comment by aforge** [comment]
Acknowledged. Will look into it tomorrow.

**Comment by or-else** [comment]
There was a similar problem on Android: some users exist in the contacts database, but some only exist as P2P conversations, like Tino.

**Comment by aforge** [comment]
I tried to reproduce the problem today but couldn't: the contacts lists were identical on Android and iOS.
Was there anything special with your setup?

**Comment by or-else** [comment]
Does not seem to be anything special. Here is Android and iOS running off the same server at the same time:
![Simulator Screen Shot - iPhone Xʀ - 2019-05-30 at 08 29 01](https://user-images.githubusercontent.com/5938143/58644040-4c29a580-82b5-11e9-81a2-ff959f697951.png)
![Screenshot_1559230082](https://user-images.githubusercontent.com/5938143/58644056-53e94a00-82b5-11e9-8913-0f51c4c3dc59.png)

**Comment by aforge** [comment]
Okay. I cannot reproduce this with my local setup for some reason.
Are you using a remote server? Or a locally built one? I've been using the docker image.

**Comment by or-else** [comment]
I'm building the server from source. Let me see if if I can come up with steps to reproduce.

I'm still busy with https://github.com/tinode/tindroid/issues/38

**Comment by aforge** [comment]
Don't worry about it then. I'll build from source too.
I'll need to build the server from source soon anyway for adding push notifications.

**Comment by or-else** [comment]
Just hit it again: user `Xena` is present in contacts but does not appear in `Find`
![Simulator Screen Shot - iPhone Xʀ - 2019-07-18 at 18 03 51](https://user-images.githubusercontent.com/5938143/61468759-b0e4b080-a986-11e9-9031-62b907e89099.png)  ![Simulator Screen Shot - iPhone Xʀ - 2019-07-18 at 18 03 56](https://user-images.githubusercontent.com/5938143/61468770-b641fb00-a986-11e9-96f5-b55316140451.png)

**Comment by aforge** [comment]
Humm.. Still can't reproduce. Is it reproducible for you?
The local contacts list is read from Users table - if something's missing, we somehow fail to store a contact in the table. I'll reexamine the codepaths writing to the table.

**Comment by or-else** [comment]
Here are steps to reproduce:

Go to FindView, enter [basic:xena] in the search field, tap on Xena in Directory. Go to ChatList, see Xena there. Go to FindView and see that Xena is not there.

**Comment by aforge** [comment]
Thanks!
https://github.com/tinode/ios/commit/c3a649b5e7d0e3b0d4d532a95d73a30272f08c74 should take care of it.
I'm going to keep this issue open for now in case we see this behavior again.

**Comment by or-else** [comment]
Looks like it's fixed.
