### ISSUE TITLE
Something wrong with auto-reconnect

### ISSUE THREAD

**Issue by or-else** [tinode/ios#31]
Something is off with auto-reconnect. The client repeatedly creates connections to the server, sends {hi} but no {login}:

```
2019/06/05 12:10:40 in: '{"hi":{"ua":"Tinodios\/1 (iOS 12.2; en); tinode-swift\/1.0","id":"151","dev":"CCE21C82-C877-4773-95BC-A903D2435274","lang":"en","ver":"0.15"}}' ip='127.0.0.1:50844' sid='dhf3tnguijE' uid=''
2019/06/05 12:10:40 in: '{"sub":{"id":"129008","topic":"usr6gesh4vSn_Q","get":{"data":{"limit":24},"sub":{"ims":"2019-06-05T01:36:29.578Z"},"desc":{"ims":"2019-06-05T01:36:29.578Z"},"what":"data sub desc"}}}' ip='[::1]:50857' sid='bV_S6PJUNG4' uid='wjKtwAryZPg'
2019/06/05 12:10:41 ws: session started nR_2zlGdunY 16
2019/06/05 12:10:41 in: '{"hi":{"ua":"Tinodios\/1 (iOS 12.2; en); tinode-swift\/1.0","id":"152","dev":"CCE21C82-C877-4773-95BC-A903D2435274","lang":"en","ver":"0.15"}}' ip='127.0.0.1:50844' sid='dhf3tnguijE' uid=''
2019/06/05 12:10:42 ws: session started 4b6b_1LlHoQ 17
2019/06/05 12:10:42 in: '{"hi":{"ua":"Tinodios\/1 (iOS 12.2; en); tinode-swift\/1.0","id":"153","dev":"CCE21C82-C877-4773-95BC-A903D2435274","lang":"en","ver":"0.15"}}' ip='127.0.0.1:50844' sid='dhf3tnguijE' uid=''
2019/06/05 12:10:43 ws: session started 3VNGbEQ74EI 18
2019/06/05 12:10:43 in: '{"hi":{"ua":"Tinodios\/1 (iOS 12.2; en); tinode-swift\/1.0","id":"154","dev":"CCE21C82-C877-4773-95BC-A903D2435274","lang":"en","ver":"0.15"}}' ip='127.0.0.1:50844' sid='dhf3tnguijE' uid=''
2019/06/05 12:10:44 ws: session started _LWpTGOz58I 19
2019/06/05 12:10:44 in: '{"hi":{"ua":"Tinodios\/1 (iOS 12.2; en); tinode-swift\/1.0","id":"155","dev":"CCE21C82-C877-4773-95BC-A903D2435274","lang":"en","ver":"0.15"}}' ip='127.0.0.1:50844' sid='dhf3tnguijE' uid=''
```

To reproduce start the server, connect the client. Shut down then restart the server. You may have to wait a few minutes before restarting.

**Comment by aforge** [comment]
How reliably can you reproduce this?
I tried reproducing today with no success. I'm using a docker setup (both the db and the server), though.

**Comment by or-else** [comment]
I'll do it again later today with the latest code. Will post results here.

**Comment by or-else** [comment]
The latest does not build:
```
error: Build input file cannot be found: '/Users/gene/ventures/tinode/ios/Tinodios/GoogleService-Info.plist'
```

**Comment by aforge** [comment]
Ah, yes.
Sorry, I've just updated the README file. Please, download GoogleService-Info.plist from Firebase and put the file under ./Tinodios/.
It's Android's google-services.json iOS equivalent.

**Comment by or-else** [comment]
I can no longer reproduce it with the latest build. Closing.

**Comment by or-else** [comment]
BTW, I'm not sure `GoogleService-Info.plist` and `google-services.json` need to be kept secret.

**Comment by or-else** [comment]
It's OK to openly publish these files:

https://groups.google.com/forum/#!msg/firebase-talk/bamCgTDajkw/uVEJXjtiBwAJ
https://stackoverflow.com/questions/37358340/should-i-add-the-google-services-json-from-firebase-to-my-repository

**Comment by haorenfsa** [comment]
mark: seems encounter same problem in v1.5

**Comment by or-else** [comment]
Is it reliably reproducible? What are the steps to reproduce? The latest release is 1.6.1. Do you see it there?
