### ISSUE TITLE
Issues in a PR

### ISSUE THREAD

**Issue by or-else** [tinode/ios#41]
Changes here look problematic to me: https://github.com/tinode/ios/commit/ad24ca9ec622a290e893aed21054b95493456825

I've added comments to the PR.

I've created this issue because I was not sure you would get a notification for comments on an already merged PR. If you did get a notification this issue can be closed.

**Comment by aforge** [comment]
Yup, thanks!
https://github.com/tinode/ios/commit/782aabf4eb1f58190932d06752fe9be6c0931964 as the fix.
