### ISSUE TITLE
 I want separate Tinodesdk。

### ISSUE THREAD

**Issue by ztimc** [tinode/ios#5]
because I see app and sdk in one project

**Comment by aforge** [comment]
What do you mean by separate tinodesdk?
A separate GH repository? Or something else?

**Comment by ztimc** [comment]
![image](https://user-images.githubusercontent.com/33918556/50724278-d403ed00-1125-11e9-8f40-10d424fda2ef.png)
Just like this.

**Comment by aforge** [comment]
Okay, this sounds reasonable.
I'll split the Tinode SDK into a framework.
