### ISSUE TITLE
Chinese translations please,thanks

### ISSUE THREAD

**Issue by KyoShio** [tinode/ios#76]
Chinese translations please,thanks

**Comment by or-else** [comment]
Sure, would love to. I just don't speak Chinese.

**Comment by PokerXu** [comment]
Just like the webapp translations.[https://github.com/tinode/webapp](url)

**Comment by or-else** [comment]
I did not translate the webapp. Someone sent a pull request (lots of thanks for that!):
https://github.com/tinode/webapp/pull/32

**Comment by or-else** [comment]
Thanks. Closing.
