### ISSUE TITLE
JSON serializer adds unnecessary backslashes

### ISSUE THREAD

**Issue by or-else** [tinode/ios#9]
The currently used JSON serializer adds backslashes for forward slashes, i.e. string `"abc/def"` becomes `"abc\/def"`.

**Comment by aforge** [comment]
This seems to have been a long-standing issue:
https://stackoverflow.com/questions/47076329/swift-string-escaping-when-serializing-to-json-using-codable

We'll perhaps have to use it as a workaround for now.

**Comment by or-else** [comment]
I just checked: js and go parse such strings correctly:

```js
var z = '{"x": "http:\/\/www.example.com\/"}';
console.log(JSON.parse(z));
```
Result:
```
{x: "http://www.example.com/"}
```

Go:
https://play.golang.org/p/0quh2bzP4hL

I'll check in Java and if it parses it correctly too then it's not a problem at all.

**Comment by or-else** [comment]
I just checked it on Android. It handles such json without any problems. We don't need to do anything. Closing.
