### ISSUE TITLE
CFBundleVersion

### ISSUE THREAD

**Issue by elisabet95** [tinode/ios#98]
hi
when I want to run on simulator I get this error :
I test it on iPhone 11, iPhone 8

> Details
Failed to install the requested application
Domain: NSPOSIXErrorDomain
Code: 22
Failure Reason: The application's Info.plist does not contain CFBundleVersion.
Recovery Suggestion: Ensure your bundle contains a CFBundleVersion.
User Info: {
    bundleURL = "file:///Users/appleland/Library/Developer/Xcode/DerivedData/Tinodios-aavztrdhtdgnsabebxzzvjqghlqp/Build/Products/Debug-iphonesimulator/Tinodios.app/";
}
--

Xcode version : Version 11.1 (11A1027)

**Comment by or-else** [comment]
The `CFBundleVersion` is assigned by build script. For whatever reason that script failed to assign version (Git not set up?). Just assign it manually and remove the build script reference. Or set up Git.

**Comment by elisabet95** [comment]
> The `CFBundleVersion` is assigned by build script. For whatever reason that script failed to assign version (Git not set up?). Just assign it manually and remove the build script reference. Or set up Git.

I get project with git command and it's work !
Thank you
